---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: 3.8.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    global:
      clusterDomain: ${SECRET_DOMAIN}
    loki:
      auth_enabled: false
      storage:
        bucketNames:
          chunks: loki.chunks
          ruler: loki.ruler
          admin: loki.admin
        type: s3
        s3:
          # s3: null
          endpoint: ${endpoint}
          region: ""
          secretAccessKey: ${secretAccessKey}
          accessKeyId: ${accessKeyID}
          s3ForcePathStyle: true
          insecure: false
      # storage:
      #   bucketNames:
      #     chunks: loki
      #     ruler: loki
      #     admin: loki
      #   s3:
      #     s3ForcePathStyle: true
      #     insecure: true
    gateway:
      replicas: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host "loki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: loki-tls
    monitoring:
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
