# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kGGy8dK5iPkIFj+Ez5Cnu981oDV0QUb/,iv:egDcrITZTsnHFj7nwwRDqZtKHg91giekCCHAfgIuqfM=,tag:PSdbLiFzyxt42QZpbtrjNw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:T/YSzBWTGBWPvrFu+tqOqW2CuZkInBMnS8yKIZOsHahvo3zzSg==,iv:ZkWQ8+8hdFi6uuT37O+LuADPj7QHF3V4botM2FHuhLs=,tag:3qvkj7U68/fJ+N8tAanIog==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:zcSRjVwH47EVE2qxSog9,iv:4TaCzvQLEvHe4W4yW/+NdhoyQcfZBGry3D1e4GUsvcQ=,tag:hRrn2ZaDlOOm/khEHsPOsw==,type:str]
    NEXTDNS_WEBADDRESS: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ1BMcjhBWm5kaXpRdmNE
            ZDZQZWllTGl3b3dpWXBJRm9xd05lRlNBbmgwCmJiNkNtMHdEVnBRZ2k4bmpVSVF2
            MjEyS3pQTjJ1VUNkb2FEQmsvQXMrVW8KLS0tIFo0WU1KNlR2dEtBTVF2VHZsekVh
            WG4zd1lNaVRPd1MrYjNaU0VXZ3M1b0kKR/HdLu6+aYZV4JTZCZA/34RgD9/lDOPz
            BhUl13hiISZYai0tssaLI6Vao4G0VLBOM4vTc1gLJ6krGwIkHQDlMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-27T00:29:01Z"
    mac: ENC[AES256_GCM,data:MfxjHxpGST/huq3yKDQrjOS9ptuNnk1WM8DoR4vm3cCiiJj/06YRt4d4uzyjtNe9dIPHyIC7ySW0O7NimbAuF7Aml3pPyD23qdgcNn5giqjhYqiQ0jCIH1xuinR7bna4KITD8aYP4EWA1PHVMoegLFYQEKAxrxghM2mPeDmjRLA=,iv:ZMcBhLYZ71/ztLhF2sIBDWpkErjKUVoQx9kFRQC5hcA=,tag:335siVh7ev3PBUp2s6fQig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
