# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:i//HR9BeUR1pWAiM3qs/fIogv7cCoMpv,iv:8QVz6CxIA/6t7IszBUN6yGaZ6g++DjxM0aHJdniij6Q=,tag:Iv24a/R09vaFWrL5kP/uHA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:fAc55sSzbRuTTjkbViBOfU/b/NBjQARhjlv+j3shHbavrpHeow==,iv:rcWmC/sV1BMAMdRJ2xJaRp4qwsS5zKdOWjrsz7mCAvs=,tag:i6xN0VJ788wc1kGKFLv1Ng==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:m7mi0TNYVYjrAZmpl0GI,iv:q/is4NLQWGazNZm4EaLmGwet1/1IPrmbsmeDYSKOxGw=,tag:kFcmaojrsnIOp0enhJKi9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MElhbmlTUzRzZENDdGJW
            dlBvT0tRK1E1OXRQUHJZTTkra1RBam44MXlzCjJ6K3U5SC85RjIrYTdYVnFRdUIy
            SGdTTmt2MXU5YW9ZcFRsMDJkMTJFZkUKLS0tIEJKNmV1Sk4xNWtaVm55UmpOS0xK
            N0I5L2l2d0E1RElHb0lIU3Rkdk40VUkKF2FJyAmZReDlH7/bIEPsVcAiex+yGF0P
            9P6rP4HdBVMefpFLfkZtQMoNeuY3PzNviFmCXs+fKhtkTGNKAMs/Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T08:08:38Z"
    mac: ENC[AES256_GCM,data:gBV0Vqqb29J8L9sCWdeS3Ca2M/yrtRFXJqeEZ2g2T0xLEYsoMxlQHyryOEJvm2zuKiuvS+Rjq7wmeQ4z+8/FJ09IocYL9iGJCIHltp5hBe9DaIXuLmaM5jlGr8ocqZIBRf/KyVfzoJ+OFjkabBUVw1/HhMR08XcVP3p+NRMb//g=,iv:kItTGgcRLhIA0rePjFOIFteFdeqDgU5/nNkOQpHOHiY=,tag:UQs2kF+shi0vc0VVVEscIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
