# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fCrzUyRRiR7Q5CavGMHRauv/UPkXK/iQ,iv:lbIWXXr81TTolwYYxvDQWrWmR4ynbTWqY02repJqoIU=,tag:xADTamRa/Hfws0uVOaTXMQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5B9TDJCeWtnoNBLlXn5123lLtsxWAOrGPnTu7zGEZfzx7+WH3A==,iv:nkNvTwW4MfYj9xRjCJPHs8hOPxtV5s1EqM5fWOyXeuc=,tag:0Own/1VFp6wlAuokQKZQlw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:JfN2FwunoGn5Uh45rBYW,iv:WSf6Stie1faNSA5/JkqlFJP4muuJSPS68dBKDaYl/DE=,tag:CZWgHpzOwXn1TVW5S7Voqw==,type:str]
    NEXTDNS_WEBADDRESS: ENC[AES256_GCM,data:iHAbySPLfhbi+6uI+DVKTpWt1wiPfzPVWMT2Wj35ifsQRu99B7ePGHRUBGTPAzs5GW0=,iv:Wbkb0nGapvwlaIEzzHgS25m/LcH4v1rcEZryHzidFdU=,tag:fB5fc66QDdBL4H4d2kaIQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOXQrbEdxTmFNOWZJbFp4
            WmI0Z3E2WFNkRThNMFFvaXhqL1h3dG1LL1ZNClJjc0hRYnVUSDFrU0xzaS9XZW1R
            OWh0Z2h4aFNQL0ROVmpESVpmUXpOMkUKLS0tIGx4VWZUWmVyYUtrS3I0NTQvYXV2
            ckhrWWM3UmZjUlRpTDFtUklqYldQVGcKYw4gNMo0j9JwJpiUBsr5yE5sxZg9DOlx
            VmfXyp7hLSHkb75paZEklyWc9qZINWRoRRNlHGwU5jMPjRVGCMa/nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T09:06:39Z"
    mac: ENC[AES256_GCM,data:Vgfv2a+Ink3F+PM+3MDfIBgvOh9/BSpK656aNYUJf+7zludXT+mVOHjKuG+c/QjmwCkPlBmFdWhHlpFHLuQuxsQWe4581pVVrbMQcQi9FkO/Fb7u+9DzAZ2G/O2JJvAv3q14lr7iTPO8XsQcTYyhPNoF4QLzHgUvKIPUASrny8w=,iv:VYenp0qFPtDtqTmjugUQaTrE28J1GiX7Zgn/JrEElk0=,tag:Fm55CWMICzGVz8twR/SAHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
