---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: subnet-router
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: tailscale-subnet-router
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: gtaylor
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicaCount: 1
