# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-subnet-router-secrets
    namespace: networking
stringData:
    tailscale-subnet-router-secrets: ENC[AES256_GCM,data:3Cdw140K1EoQaYyHgw0sXP3qrh6BNt5OvZnjF8AWKDRPWTLOm3yBB6ZezESLZHR3ByOA1M65T93F,iv:MWSIelATqnOvcI34e+972KxW5eICEOaRHX0jTvksiQc=,tag:DPXK1uqlsmphztOFYnlobg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweVhvb1RpNTd1aTZHL3ZJ
            TGsva0V6QWdNVlpRVm1GV245Skc0YmtuVGg0CllGSDJDbEVGL2hTdVlMWWFLeWQy
            cnhzeDlnblBhN2JxazlFbmRjTFdhd0kKLS0tIE5WK0Nqc0Y3ZVF5Q3FOOFNWSmFm
            TEtHY3RWN2U2NXdxd1htZkV0bXNCYUUKW7bZRDuSCrQlx8cdkB+Ik0NKpbbo+6Eg
            vqmGDMgi7gIjlijnLK+9j0HrjP+7lv3az5uxNUAOElQxMYUfQ/2W0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T11:44:57Z"
    mac: ENC[AES256_GCM,data:eM4ICxVJRPmaip6YloF2hUwLR2w55mG7JFxD+ViW/Cqzlekb03xZwMIQaF+ZWvOaqOUsZG5iTGB6OQuzw2/wY1TTUM1vCMR3E+HXyV0Pr//vqvgQmchyK5/2ZgUdXTlETrugI7CdsRA0Qc6qG6d8Y4jLElZYR35JlKRQHiJx7NI=,iv:Yghr6JJgwLD2E4eMk6xS+B+PPmt8/bRKp/5cqPJia/g=,tag:x2CwalhSbW3iZdD1zXEkXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
