---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paper-tiger-delete-me
spec:
  storageClassName: s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /var/lib/www/html
              name: paper-tiger-delete-me
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: paper-tiger-delete-me
          persistentVolumeClaim:
            claimName: paper-tiger-delete-me
            readOnly: false
