# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: csi-s3-secret
    namespace: kube-system
stringData:
    accessKeyID: ENC[AES256_GCM,data:/9ihUF9/bTwTO48DqKkO2AbBpREq2Ig=,iv:LXlq3/eW/JpwHFs9mMpL/J6DcguMUhKf2plXj2NFSRA=,tag:7GoWI3woQg0jNuPwpwEJbA==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:OsMdmVnWjQukDatNdBAUieZZpO6F06Y5uYjU5/r3ymw=,iv:X88PqU+1dcdMO2tKiSomBK16Bn/I6zDdivqIs48wH+8=,tag:BLsx3bmrXUnRGADknMlN/w==,type:str]
    endpoint: ENC[AES256_GCM,data:9FygHvO0mdm7RuIjWbBbDMN15LiOVQ==,iv:VGrvP741GkjmypFxKgC85XpmVtKvGLnj1/QpYJ0/i+w=,tag:+u6rTjtP+1/LJVho2RLAiQ==,type:str]
    region: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL054aThZTWtITTcrQThD
            N1prQmJmT2JuaVd2UForQkJ5Z0ROb3hVQ0h3CnZsN2t4VDJVaXJNWUN4YVh6SnM3
            VXJiK0hUOHFNalZhVmpDRnNFU1R2Y0EKLS0tIEx0ZFE2VzBXT0d5R09wV0ZjeTRF
            SmJpNEhlNzduTzZqZnZyTVlnQ1dnS2sKkLtDcQ+wf+fOMJPC7x7KptQ6xIDTczTL
            Kxn5d/gy+Mwk9Jbx05MJMdIdyaBVlGl/zX0Ro35bG1JL7mQg2W/wkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-04T00:58:29Z"
    mac: ENC[AES256_GCM,data:csby76Bl8dt90/p9KbDZ85PVWbOa/XXJzT8Pj3HhuwxHVnkNHKwejb6+Lj/URpZgOVghTaBUB84D4cN5ovDyqHZlFknYgD8Do7Sz5SNd83FXDLOy93sSeyLWJx57mZ3dVcy42gqHUHLj0ZoCR/v1QvwmEuvauHPrlQtyyxmwFpY=,iv:n0uXjc+0jwmC5dSPlWFqpku7BIe+HMJp+2nXzDn9wMU=,tag:fqINzkD8KxQuLziiSYSStQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
