---
kubernetes:
  children:
    master:
      hosts:
        k8s-1:
          ansible_host: 10.1.5.51
    worker:
      hosts:
        k8s-worker-1:
          ansible_host: 10.1.5.61
        k8s-worker-2:
          ansible_host: 10.1.5.62
