# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:qZKexPAc1BuCtmx9ijNgNwNWZOa4vCoj,iv:k2L9TDo8Vbm6fm3fUgHkLA8nlerArVuI+m/2B7UEERI=,tag:u3yvySSCns4tivOQgpQDWA==,type:str]
    api-key: ENC[AES256_GCM,data:Kls/iDtfjQedY78UafOaDjEykwZ6E3R1ktQugjIEkcb+/mqUQA==,iv:pnne8JQU8lkTy8QbNDtHgaC+83iQwdaWoSj3MltKGm8=,tag:U0vRMYBisI8WcSqIrOfljA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVHBSSXJLTEEyTUlIYVVk
            bjY2eVJ1UithdktjdjJXVmszRktYNEtNRkVnCklrcTM5Z0U4aXJOZHNYZkcydVhs
            ZmFsNEpRWUM5K1Bkd1ZGUkROdWpEWmsKLS0tIE1sZ0pSUWw4SzFZN3lEeEhxbW4r
            MEFpYlBuVk03VTZuelV4MlJDVnV2RG8KiGgOcq72X4GeWuNNs+DGdnTIdH9ug6dk
            c3KhDoVfydkE6pmGJzP+8TIa2/iei6z0gT0ahNow9MUpFgOswwvj7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T08:08:38Z"
    mac: ENC[AES256_GCM,data:5mwpvKkaRDKTq4LGkVU6dybyjCkcGFkUIHCKdwmEq/B4NdJVvz0yc2X5giYpsbE5enATWpjKubdq6/xh1/V7VThAWOgb3xtmha2RhZ3m2hzRjnV4GUgcJZAHFsbB4yJI0fOKeiHV6hbzVZwJu6qQd1Kr5L6oZVyW4bpFjHpTvTw=,iv:aA6RjIcOvd0RDh8Hwzx/gPBtOrCsD9th8a5rThJecP0=,tag:Jpi6m2rLQ/fdsTAAJERg6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
