# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:FiZu2/eGoaSIluQ0ewtXMBVt5ml9lXDC,iv:Of8vNxXd/MfD0npOX6DFcjAQPs1uYEN1pwZdScHpesk=,tag:sxG4z3Djo3vnz1bWN7D+GQ==,type:str]
    api-key: ENC[AES256_GCM,data:1VFv8NCERzC4zbVc3YoIrOdxIrKM/niYKXyUK+J+yxEHzHZeyg==,iv:JQr6yG7Cs44bwrbQeUcCmx93farAmjLW4XII31x4baM=,tag:+8K4V/dAUoy1Y3rryNnW+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZUU0dHdVNUo5NjhiTmxu
            dWVKMmE2ajFFc2l2Nm01em9GeXNra1BMRjF3CjdoTTZYTnl6N2FtaWRqcTE2RVI2
            Vi9ickd6VlhuYXlvbzBaRGwyclAvaUEKLS0tIGRDR1pyVnBtTkY5Q3VVNmI2L21l
            Zm1xTzc5QWY3ZG5VOVBnOUVxNmhabk0KzP6iQN6yeR9f2iL0Sq+XXHn5ejB/0/mA
            KXXepgedFH4mNYvlWK8/8M5Xm4VRD6MC60mnHa2Pw0JHxMVfUVdBMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T07:57:49Z"
    mac: ENC[AES256_GCM,data:8vBCylZ4smcSw+hr6ZasdZWRGCyE+Z9eZaRA6oIrihrh4kv/k7jkqxtFEgiviAemRjHQqOhHsISmEb4VoXrpf0QJdM2V1cX/4KYHyS3ba9ie6IZ9hdW48crpEz5v1am+98Pdd/LoXKyMt3C8WYLr5w7srs3VmdTPZYqh+id1Oho=,iv:8JXM+JM/Q2b4B6qJmRlBIYhP+U3pLLSBQLgRuszNvNM=,tag:PCdmAWtQ/YeFTd9RaDQufA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
