# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:R4S+sh+a/HR54fhs5ghAcye0M6kK3JNUe3pbWHuynKhG1SSL2Q==,iv:eTCJP7xscP+KBnIyuXXSjCsNa+8owztkaiVMBLnbXHE=,tag:DuPdGy3pvaOttjhQzfKJsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN1lGb05VL0FVOEE3MXA2
            MndVQ0Rkam5YTHpua3RiMkZiZ3pYYzNWV1ZZClJYMnlXSHZQWURBOTZUVjhlK2t6
            OWt0SzRYcjFqM3ArckJsM0FtSHQxWFEKLS0tIGg4YTZVMjNDUUhSSnByaW5kY0NG
            KzRoVm11UmxBWEIxVTgvdU52TVVZQ28KFg0X/JSxjVBAp8Joh5fsJWGDPyQvzvkY
            ofOY/+rZDvvezEMV/elNnY6lrbToMHwerv+eSKkRVZZeSJKTUukG2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T08:08:38Z"
    mac: ENC[AES256_GCM,data:FFf+E16UbemNEiJiYhp3ae+8Xgv1iLBK4wvwZvZXkEIWfLYJJyYNhCHdiQa12eeGQilCXca9f2iQoAOxUCXD6LEKQ0SYDG4ayry/u2+LRWaxknFQJfM6s/XhFTvfq3iuvbp+L4hCSmFX/V6s+a4q/hE600HAoAM0o3cBX0mbJII=,iv:x4fyQtVeTcdq5aLwPWedDcq4Q8xIPmp1P6e6jTCe6xM=,tag:LuEZV+MhZTUTdEBwHpj+vQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
