# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dqxe0rvvvssa8Q==,iv:jLlw58OdZsmF5ViENg8K7VD+xRwtievmOVRWOUAQu4k=,tag:K0sr5osmGxb+GnXkmZcaPg==,type:str]
    SECRET_GATEWAY: ENC[AES256_GCM,data:RJ+C5Tx/7/47,iv:T+3C4j6/07jl7S/HaVWXwxUeu1ajqgVDIhYhrUeEIY0=,tag:M7XHFcQWV7i+Uxg/ByqWGA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YYdJJtXfhIyXlTQbvSFh0Bbc/BvgZOt+,iv:dPV32CQVRRjCxbSV4ZFet1BRJfu3I+EPAs7skNuQeEs=,tag:mn0lXeiqVHA7uJoPbsUYaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1blM2aGxLNnhBcE96NFI5
            OVIzR0ZxUlRWL25ubDZvV1FlLzlpZU9MblhJCnFXZXZ4VHQxTkwwZDhJUjFnZFZs
            U1kzRXh0MlNYQVlONjJwTUtNS0pqM2sKLS0tIGsvbUZBMzR6bkMxY3lnTXRIYjMv
            ZHZDejlVa0hOSU00T1FOZ3k5MzhLckkKUvNBf4xHXKbFY8sTQcY2LUS0Y/OA3wDn
            ogcGYjA7vQ1/7YIw9ZOWkMivv/CWuxNVFAd06KP3U0fMPiBFRfNsVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-27T00:29:01Z"
    mac: ENC[AES256_GCM,data:Picbf0AsE+eyTQNczjAIyA4xblJysEW9Wm4OqbcFxSjErC7YZmB5UR4yiopx72tWtAIy8EF8ly4CmrAg8DkISRcbhmbLFoPNoZOzmMD6NyvkaLgln5D7dPfmtDXMmJojFVvE+Rmvg07nDd0nXX77zCy/n5xUx8MrN1V9oLb+biA=,iv:43f5LEwP+9YCL0MAolNe2zPMvU0m5tG8hPN9+RmbiEo=,tag:QDzupBR6D9Phi4I/PxBTGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
