---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - ${BOOTSTRAP_AGE_PUBLIC_KEY}
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - ${BOOTSTRAP_AGE_PUBLIC_KEY}
  - path_regex: terraform/cloudflare/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - ${BOOTSTRAP_AGE_PUBLIC_KEY}
  - path_regex: provision/kubeconfig.ya?ml
    encrypted_regex: "^(data|certificate-authority-data|server|client-certificate-data|client-key-data)$"
    key_groups:
      - age:
          - ${BOOTSTRAP_AGE_PUBLIC_KEY}
