---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: denis-ev
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: tailscale-subnet-router
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: denis-ev
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: latest
    tailscale:
      secretName: tailscale-auth
      secretKey: TS_AUTH_KEY
    routes:
      - "10.1.5.0/24"
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 64Mi
