# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: networking
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:C8XCEvGUjQ6kEqADn+aF+mnAwDip5J4jmelWmo/M0T/XSDiPYEpoIV8Q6tBCQdCbT0ISgTWmGGbA,iv:6BSBXXwkGquHvSBr9sNWuFzz6/A5Ymp79jEeICBNYoA=,tag:gfD9J+xNy+BvQ1iyzQY45Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z0Q1bXBGQ1ZSYllUSnY3
            OEhzTlpyeGNpNHJNQ0NrV1BkcFFxZ1p5TUYwCmR2WlpsZThHRnBqYS9ac3RXelh1
            U250eWg2N0J4bEplbUFTOWs3S2pVZ2MKLS0tIGNDMjdxeGpiT1BKd2dGVXpUUDY5
            NmF0UnUvUFdHUDNzRFRjS0N3ME93d2sKS5Tq3ZOudlXuZqWoYx42wyxDINC7RcG0
            Jam68YiEK5D6kwCQWUrmcm11mNj/kgd3FtEKhbuPxD8XHO55mvu4kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T09:06:48Z"
    mac: ENC[AES256_GCM,data:TLt0KtYhQ5eEk0jAhMGUTUPZrKWzxZAgjIgfbUAuobFuQMO45gtGenPrK4wmJyQTJao/QbKsnG0mhCj0+Nw/eg19Xwv8VxOurxVdZAFX+JXbtilhXzFo7J5D2RObYjbAlczOAH6ssDBPtzxgAV7/mEavecyea8P3xjy75E02Ye4=,iv:g+bPjCi2b9MWSOBs55BRVr8U5lGgzigsl9027WXREfs=,tag:cgMbIL50+aaKKO8O5YsCpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
