# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cPqBUX3SpAUufNUhpwcH1f6jEBrWpFl/aqGMqQRGRDEEfWwUFk/s7Q==,iv:T4EJk8ZhsvvzQiXVWBxVZtiqnx7O1DnwInZIqw6F21k=,tag:JERRJIT1adpuaBbr+tf52Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMLzBaWnJLL0ljT1NBQ0lF
            eEIwREJFeVJoRCtqVzhvRUg5OFN2cm5aMWxnCjhoSy9iU1pVL0h0TjQ1VWJvbGVn
            MUFpejd2S1dxeWxnZzBRekhzYUtaYVkKLS0tICtjVmZFTnVKSGMyNUJva216Tnhv
            cGw1MEs0UDlHU0t1VmNidWJJaTdQVncKoMa+zjZcAPKg42LZzoDF+rOn+QLZC+kb
            dMnD0WZyrGqkRcrTLam/ZGUqkUgSesUAxMdphqi4cHyhMLiP4+Hnjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T09:31:37Z"
    mac: ENC[AES256_GCM,data:NzKIdoL9m/a+9U16GN4p+zlFOfyGweM2gGV1j1j4inpuntm6D1AvDtLoI5TTSTDMPh0OLyUTTEflnyf0BNicRLam2+PloA0w/+LiC2DagZBoJgGKhXR2alLCv0QnguyQ6zHgdGNwtLtkjUfLOXVQVhoDUno34N+hahbnRrcy7AY=,iv:0uxWosj2KFeEzWgN9r/9R6Jgem2f71Jmv4G8hwgBk8A=,tag:9N8pT3xPc66YEmWD13qoOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
