# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:N35gAw3BWGCtavQfNwfZ3a2esmqTDYyJp6bj6VDEMOVaO+yGIWDGUg==,iv:/rtiOQDPzYbYsz/3mrJ+CDFnCQ/yLUfE/HbXZyPfOuA=,tag:Iyth/bd3zJ8TA7cXFqPG9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaTI3S05qeHM3b25zNll0
            eXpYbjZOYXl0YXF1SjJCempyb2JaNlVXZDA0CjlkMi9tMVgwZjhsQ2dlNlJTcGJN
            aFRqblA3R2dnVG05cWVNTjVWUG8xbTQKLS0tIFlTZ1NzUU02U3ZHOVRNTE5icTk1
            dCt4V0V6UDdCaEFjcFI5QnRKRjAxR00K+VPGW2Osl4y2+YkVNBeGcJeSjIvsN+uh
            bWNuPq5cHGnGzetwF505qzq2UMRDpLhUBXVipPuZKTRe+8HcYKnDBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T07:57:49Z"
    mac: ENC[AES256_GCM,data:3L6tjhimJdEGEbaZb2K0P6dE0YkrAX0vOF6TSiXhZyMnXjkpWaeudRORSV/OKtM8H9XU2XC/3blBlTXgATaZtvn1z96CIKWSP9JD8IslYt8ewoKpnIlO9bi1gvJKQ9wczCVYaedF+E3qw1UsaZpCCCLXkJTtx0LIvlNqH5mvjCk=,iv:tNdQSIiFLea/9IE0s6n60yc2FZ9HUeMhs/7BKIstgKw=,tag:5sKes8MIgsCEk8RbEK8uBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
