---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hajimari
data:
  defaultSearchProvider: "DuckDuckGo"
